/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package circuscharlie;

import org.junit.jupiter.api.Test;

import circuscharlie.Main;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
